CREATE TABLE t_inventory (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          sku_code VARCHAR(255),
                          quantity INT,
                          PRIMARY KEY (id)
);
